### ISSUE TITLE
no es importante (borrar)

### ISSUE THREAD

**Issue by emilia-montauban** [zEncrypte/AntiSuS#2]
![a668bdb9a0971e3d7889b9a47b285b34](https://github.com/zEncrypte/AntiSuS/assets/88011060/0a520713-2175-4afc-989d-4527904d59b6)
![71baad739acbade4e22f33ac7a88882e](https://github.com/zEncrypte/AntiSuS/assets/88011060/8e43adac-584f-4bee-9b1a-e5254f27b4ef)
n
![68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f313035393832393636353236383736383839382f313131333534343331343939323231343035372f506963736172745f32332d30352d31305f31382d32352d31392d3930](https://github.com/zEncrypte/AntiSuS/assets/88011060/d3a2f6fc-9625-42cf-a84f-ab1ee6a73af9)
![ef9681f38392bd6612166f1beb5f923f](https://github.com/zEncrypte/AntiSuS/assets/88011060/09345b60-e3f9-4020-9dd5-096546aed1a9)

**Comment by zEncrypte** [comment]
nice pics
